// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteToken(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetToken(ctx context.Context, id int64) (Token, error)
	GetTokenForUpdate(ctx context.Context, id int64) (Token, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListTokens(ctx context.Context, uID int64) ([]Token, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (Token, error)
}

var _ Querier = (*Queries)(nil)
